version: '3'

volumes:
  db_dev: {}

services:

  api:
    build:
      context: ../../
      args:
        DEVELOPMENT: "True"
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../../news_provider:/usr/src/app # Link container volume to local files
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "8000:8000"
  
  database:
    image: postgres:9.5
    restart: on-failure
    container_name: news_database
    env_file:
      - .env
    volumes:
        - db_dev:/var/lib/postgresql/data
    expose:
      - 5432