version: '3'

volumes:
  db_dev: {}
  api_media: {}
  static_volume: {}

services:

  api:
    build: ../../
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn news_provider.wsgi:application -b 0.0.0.0:8000 --workers 4 --timeout 120"
    container_name: news_provider_api
    volumes:
      - api_media:/usr/src/app/media
      - static_volume:/usr/src/app/static
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "8000:8000"
  
  database:
    image: postgres:12
    restart: on-failure
    container_name: news_database_prod
    env_file:
      - .env
    volumes:
        - db_dev:/var/lib/postgresql/data
    expose:
      - 5432

  nginx:
    build: ../../nginx
    ports:
      - 82:80
    volumes:
    - static_volume:/usr/src/app/static
    depends_on:
      - api